### ISSUE TITLE
如何解决ValueError: cannot reshape array of size 1288 into shape (28,28)

### ISSUE THREAD

**Issue by Harry-Bai** [Haoyan-Guan/CAReg#6]
Getting transformed features...
Calculating distances...
Maximum distance from cluster centers is 1.31
initial embedding size :  (137984, 1536)
final embedding size :  (13798, 1536)
  0%|                                                                                                       | 0/10 [29:48<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 685, in <module>
    main()
  File "train.py", line 193, in main
    gt_list_px_lvl, gt_list_img_lvl, gt_list, gt_mask_list = test_patchcore2(models, inference_round, fixed_fewshot_list,
  File "train.py", line 673, in test_patchcore2
    anomaly_map = score_patches[:,0].reshape((28,28))
ValueError: cannot reshape array of size 1288 into shape (28,28)

**Comment by Haoyan-Guan** [comment]
The size of your input image maybe wrong?
